version: "2"

linters:
  default: standard

issues:
  max-issues-per-linter: 50
  max-same-issues: 0
  new: false
  fix: false
  uniq-by-line: true
  whole-files: false

run:
  timeout: 5m
  go: "1.24.2"
  concurrency: 4
  allow-parallel-runners: true

