// Code generated by MockGen. DO NOT EDIT.
// Source: pr_storage.go
//
// Generated by this command:
//
//	mockgen -source=pr_storage.go -destination=mock/pr_storage_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "app/internal/domain"
	models "app/internal/repository/models"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPRStorage is a mock of PRStorage interface.
type MockPRStorage struct {
	ctrl     *gomock.Controller
	recorder *MockPRStorageMockRecorder
	isgomock struct{}
}

// MockPRStorageMockRecorder is the mock recorder for MockPRStorage.
type MockPRStorageMockRecorder struct {
	mock *MockPRStorage
}

// NewMockPRStorage creates a new mock instance.
func NewMockPRStorage(ctrl *gomock.Controller) *MockPRStorage {
	mock := &MockPRStorage{ctrl: ctrl}
	mock.recorder = &MockPRStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPRStorage) EXPECT() *MockPRStorageMockRecorder {
	return m.recorder
}

// CreatePRReviewerInstance mocks base method.
func (m *MockPRStorage) CreatePRReviewerInstance(ctx context.Context, prID domain.PRID, reviewerID domain.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePRReviewerInstance", ctx, prID, reviewerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePRReviewerInstance indicates an expected call of CreatePRReviewerInstance.
func (mr *MockPRStorageMockRecorder) CreatePRReviewerInstance(ctx, prID, reviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePRReviewerInstance", reflect.TypeOf((*MockPRStorage)(nil).CreatePRReviewerInstance), ctx, prID, reviewerID)
}

// CreatePullRequest mocks base method.
func (m *MockPRStorage) CreatePullRequest(ctx context.Context, prID domain.PRID, prName string, prAuthorID domain.UserID) (*models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePullRequest", ctx, prID, prName, prAuthorID)
	ret0, _ := ret[0].(*models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePullRequest indicates an expected call of CreatePullRequest.
func (mr *MockPRStorageMockRecorder) CreatePullRequest(ctx, prID, prName, prAuthorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePullRequest", reflect.TypeOf((*MockPRStorage)(nil).CreatePullRequest), ctx, prID, prName, prAuthorID)
}

// DeletePRReviewerInstance mocks base method.
func (m *MockPRStorage) DeletePRReviewerInstance(ctx context.Context, prID domain.PRID, reviewerID domain.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePRReviewerInstance", ctx, prID, reviewerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePRReviewerInstance indicates an expected call of DeletePRReviewerInstance.
func (mr *MockPRStorageMockRecorder) DeletePRReviewerInstance(ctx, prID, reviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePRReviewerInstance", reflect.TypeOf((*MockPRStorage)(nil).DeletePRReviewerInstance), ctx, prID, reviewerID)
}

// GetAllOpenPullRequests mocks base method.
func (m *MockPRStorage) GetAllOpenPullRequests(ctx context.Context) ([]models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOpenPullRequests", ctx)
	ret0, _ := ret[0].([]models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllOpenPullRequests indicates an expected call of GetAllOpenPullRequests.
func (mr *MockPRStorageMockRecorder) GetAllOpenPullRequests(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOpenPullRequests", reflect.TypeOf((*MockPRStorage)(nil).GetAllOpenPullRequests), ctx)
}

// GetPullRequestByID mocks base method.
func (m *MockPRStorage) GetPullRequestByID(ctx context.Context, prID domain.PRID) (*models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullRequestByID", ctx, prID)
	ret0, _ := ret[0].(*models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullRequestByID indicates an expected call of GetPullRequestByID.
func (mr *MockPRStorageMockRecorder) GetPullRequestByID(ctx, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullRequestByID", reflect.TypeOf((*MockPRStorage)(nil).GetPullRequestByID), ctx, prID)
}

// GetPullRequestsByReviewerID mocks base method.
func (m *MockPRStorage) GetPullRequestsByReviewerID(ctx context.Context, reviewerID domain.UserID) ([]models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullRequestsByReviewerID", ctx, reviewerID)
	ret0, _ := ret[0].([]models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullRequestsByReviewerID indicates an expected call of GetPullRequestsByReviewerID.
func (mr *MockPRStorageMockRecorder) GetPullRequestsByReviewerID(ctx, reviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullRequestsByReviewerID", reflect.TypeOf((*MockPRStorage)(nil).GetPullRequestsByReviewerID), ctx, reviewerID)
}

// GetReviewersFromPR mocks base method.
func (m *MockPRStorage) GetReviewersFromPR(ctx context.Context, prID domain.PRID) ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewersFromPR", ctx, prID)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviewersFromPR indicates an expected call of GetReviewersFromPR.
func (mr *MockPRStorageMockRecorder) GetReviewersFromPR(ctx, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewersFromPR", reflect.TypeOf((*MockPRStorage)(nil).GetReviewersFromPR), ctx, prID)
}

// UpdatePullRequestStatus mocks base method.
func (m *MockPRStorage) UpdatePullRequestStatus(ctx context.Context, prID domain.PRID, status domain.PRStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePullRequestStatus", ctx, prID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePullRequestStatus indicates an expected call of UpdatePullRequestStatus.
func (mr *MockPRStorageMockRecorder) UpdatePullRequestStatus(ctx, prID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePullRequestStatus", reflect.TypeOf((*MockPRStorage)(nil).UpdatePullRequestStatus), ctx, prID, status)
}
