// Code generated by MockGen. DO NOT EDIT.
// Source: team_storage.go
//
// Generated by this command:
//
//	mockgen -source=team_storage.go -destination=mock/team_storage_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "app/internal/domain"
	models "app/internal/repository/models"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTeamStorage is a mock of TeamStorage interface.
type MockTeamStorage struct {
	ctrl     *gomock.Controller
	recorder *MockTeamStorageMockRecorder
	isgomock struct{}
}

// MockTeamStorageMockRecorder is the mock recorder for MockTeamStorage.
type MockTeamStorageMockRecorder struct {
	mock *MockTeamStorage
}

// NewMockTeamStorage creates a new mock instance.
func NewMockTeamStorage(ctrl *gomock.Controller) *MockTeamStorage {
	mock := &MockTeamStorage{ctrl: ctrl}
	mock.recorder = &MockTeamStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamStorage) EXPECT() *MockTeamStorageMockRecorder {
	return m.recorder
}

// CreateTeam mocks base method.
func (m *MockTeamStorage) CreateTeam(ctx context.Context, teamName string) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeam", ctx, teamName)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTeam indicates an expected call of CreateTeam.
func (mr *MockTeamStorageMockRecorder) CreateTeam(ctx, teamName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeam", reflect.TypeOf((*MockTeamStorage)(nil).CreateTeam), ctx, teamName)
}

// CreateUserTeamInstance mocks base method.
func (m *MockTeamStorage) CreateUserTeamInstance(ctx context.Context, teamID domain.TeamID, userID domain.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserTeamInstance", ctx, teamID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserTeamInstance indicates an expected call of CreateUserTeamInstance.
func (mr *MockTeamStorageMockRecorder) CreateUserTeamInstance(ctx, teamID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserTeamInstance", reflect.TypeOf((*MockTeamStorage)(nil).CreateUserTeamInstance), ctx, teamID, userID)
}

// GetTeamByID mocks base method.
func (m *MockTeamStorage) GetTeamByID(ctx context.Context, teamID domain.TeamID) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamByID", ctx, teamID)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamByID indicates an expected call of GetTeamByID.
func (mr *MockTeamStorageMockRecorder) GetTeamByID(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamByID", reflect.TypeOf((*MockTeamStorage)(nil).GetTeamByID), ctx, teamID)
}

// GetTeamByName mocks base method.
func (m *MockTeamStorage) GetTeamByName(ctx context.Context, teamName string) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamByName", ctx, teamName)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamByName indicates an expected call of GetTeamByName.
func (mr *MockTeamStorageMockRecorder) GetTeamByName(ctx, teamName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamByName", reflect.TypeOf((*MockTeamStorage)(nil).GetTeamByName), ctx, teamName)
}

// GetTeamByUserID mocks base method.
func (m *MockTeamStorage) GetTeamByUserID(ctx context.Context, userID domain.UserID) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamByUserID", ctx, userID)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamByUserID indicates an expected call of GetTeamByUserID.
func (mr *MockTeamStorageMockRecorder) GetTeamByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamByUserID", reflect.TypeOf((*MockTeamStorage)(nil).GetTeamByUserID), ctx, userID)
}

// GetUsersByTeam mocks base method.
func (m *MockTeamStorage) GetUsersByTeam(ctx context.Context, teamID domain.TeamID) ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByTeam", ctx, teamID)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByTeam indicates an expected call of GetUsersByTeam.
func (mr *MockTeamStorageMockRecorder) GetUsersByTeam(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByTeam", reflect.TypeOf((*MockTeamStorage)(nil).GetUsersByTeam), ctx, teamID)
}
