// Code generated by MockGen. DO NOT EDIT.
// Source: stats_cache.go
//
// Generated by this command:
//
//	mockgen -source=stats_cache.go -destination=mock/stats_cache_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "app/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStatsCache is a mock of StatsCache interface.
type MockStatsCache struct {
	ctrl     *gomock.Controller
	recorder *MockStatsCacheMockRecorder
	isgomock struct{}
}

// MockStatsCacheMockRecorder is the mock recorder for MockStatsCache.
type MockStatsCacheMockRecorder struct {
	mock *MockStatsCache
}

// NewMockStatsCache creates a new mock instance.
func NewMockStatsCache(ctrl *gomock.Controller) *MockStatsCache {
	mock := &MockStatsCache{ctrl: ctrl}
	mock.recorder = &MockStatsCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsCache) EXPECT() *MockStatsCacheMockRecorder {
	return m.recorder
}

// DecrementAssignCountByUserID mocks base method.
func (m *MockStatsCache) DecrementAssignCountByUserID(ctx context.Context, userID domain.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementAssignCountByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementAssignCountByUserID indicates an expected call of DecrementAssignCountByUserID.
func (mr *MockStatsCacheMockRecorder) DecrementAssignCountByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementAssignCountByUserID", reflect.TypeOf((*MockStatsCache)(nil).DecrementAssignCountByUserID), ctx, userID)
}

// GetAssignCountByUserID mocks base method.
func (m *MockStatsCache) GetAssignCountByUserID(ctx context.Context, userID domain.UserID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssignCountByUserID", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssignCountByUserID indicates an expected call of GetAssignCountByUserID.
func (mr *MockStatsCacheMockRecorder) GetAssignCountByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssignCountByUserID", reflect.TypeOf((*MockStatsCache)(nil).GetAssignCountByUserID), ctx, userID)
}

// IncrementAssignCountByUserID mocks base method.
func (m *MockStatsCache) IncrementAssignCountByUserID(ctx context.Context, userID domain.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementAssignCountByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementAssignCountByUserID indicates an expected call of IncrementAssignCountByUserID.
func (mr *MockStatsCacheMockRecorder) IncrementAssignCountByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementAssignCountByUserID", reflect.TypeOf((*MockStatsCache)(nil).IncrementAssignCountByUserID), ctx, userID)
}

// SetAssignCountByUserID mocks base method.
func (m *MockStatsCache) SetAssignCountByUserID(ctx context.Context, userID domain.UserID, count int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAssignCountByUserID", ctx, userID, count)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAssignCountByUserID indicates an expected call of SetAssignCountByUserID.
func (mr *MockStatsCacheMockRecorder) SetAssignCountByUserID(ctx, userID, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAssignCountByUserID", reflect.TypeOf((*MockStatsCache)(nil).SetAssignCountByUserID), ctx, userID, count)
}
