// Code generated by MockGen. DO NOT EDIT.
// Source: tx_manager.go
//
// Generated by this command:
//
//	mockgen -source=tx_manager.go -destination=mock/tx_manager_interface_mock.go -package=mock TxManager
//

// Package mock is a generated GoMock package.
package mock

import (
	txmanager "app/pkg/txmanager"
	context "context"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// GetExecutor mocks base method.
func (m *MockTxManager) GetExecutor(ctx context.Context) txmanager.Executor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecutor", ctx)
	ret0, _ := ret[0].(txmanager.Executor)
	return ret0
}

// GetExecutor indicates an expected call of GetExecutor.
func (mr *MockTxManagerMockRecorder) GetExecutor(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecutor", reflect.TypeOf((*MockTxManager)(nil).GetExecutor), ctx)
}

// WithReadOnly mocks base method.
func (m *MockTxManager) WithReadOnly(ctx context.Context) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithReadOnly", ctx)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// WithReadOnly indicates an expected call of WithReadOnly.
func (mr *MockTxManagerMockRecorder) WithReadOnly(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithReadOnly", reflect.TypeOf((*MockTxManager)(nil).WithReadOnly), ctx)
}

// WithTx mocks base method.
func (m *MockTxManager) WithTx(ctx context.Context, isoLevel pgx.TxIsoLevel, accessMode pgx.TxAccessMode, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, isoLevel, accessMode, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockTxManagerMockRecorder) WithTx(ctx, isoLevel, accessMode, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockTxManager)(nil).WithTx), ctx, isoLevel, accessMode, fn)
}
